# gmake
# This file is automatically generated for client.mk.
# Do not edit. Edit /Users/kaze/.mozconfig instead.
# To create a new .mozconfig file, you can visit,
#   http://webtools.mozilla.org/build/config.cgi

# PATH=/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin
MOZ_BUILD_PROJECTS=ppc i386
MOZ_UNIFY_BDATE=1
MOZ_POSTFLIGHT_ALL+=build/macosx/universal/flight.mk
# ppc --target=powerpc-apple-darwin9.6.0 is used by configure (not client.mk)
# i386 --target=i386-apple-darwin9.6.0 is used by configure (not client.mk)
# ppc --with-macos-sdk=/Developer/SDKs/MacOSX10.2.8.sdk is used by configure (not client.mk)
# i386 --with-macos-sdk=/Developer/SDKs/MacOSX10.4u.sdk is used by configure (not client.mk)
# --with-macos-sdk=/Developer/SDKs/MacOSX10.4u.sdk is used by configure (not client.mk)
# --enable-macos-target=10.4 is used by configure (not client.mk)
MOZ_OBJDIR=$(TOPSRCDIR)/../obj-$(CONFIG_GUESS)
MOZ_MAKE_FLAGS=-j2
# --enable-application=composer is used by configure (not client.mk)
# --enable-optimize is used by configure (not client.mk)
# --disable-debug is used by configure (not client.mk)
# --disable-tests is used by configure (not client.mk)
# --with-pthreads is used by configure (not client.mk)
# --enable-default-toolkit=mac is used by configure (not client.mk)
# --with-macos-sdk=/Developer/SDKs/MacOSX10.4u.sdk is used by configure (not client.mk)
# --disable-shared is used by configure (not client.mk)
# --enable-static is used by configure (not client.mk)
# --enable-necko-protocols=http,ftp,file,jar,viewsource,res,data is used by configure (not client.mk)
# --enable-extensions=default spellcheck is used by configure (not client.mk)
# --enable-single-profile is used by configure (not client.mk)
# --disable-profilesharing is used by configure (not client.mk)
# --enable-mathml is used by configure (not client.mk)
# --enable-svg is used by configure (not client.mk)
# --disable-canvas is used by configure (not client.mk)
